In [1]:
import sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 데이터 적재
우리가 사용할 데이터셋은 머신러닝과 통계 분야에서 오래전부터 사용해온 붓꽃(irs) 데이터셋이다.
이 데이터는 scikit-lrean의 datasets 모듈에 포함되어 있다. load_iris 함수를 사용해서 데이터를 적재한다.

In [3]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print("iris_dataset의 키 : \n",iris_dataset.keys())

iris_dataset의 키 : 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [6]:
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...


In [15]:
print("타깃의 이름:",iris_dataset['target_names'])
print("특성의 이름 :\n",iris_dataset['feature_names'])
print("data 의 크기 : \n",iris_dataset['data'].shape)
print("data의 처음 다섯 행 : \n",iris_dataset['data'][:5])

타깃의 이름: ['setosa' 'versicolor' 'virginica']
특성의 이름 :
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
data 의 크기 : 
 (150, 4)
data의 처음 다섯 행 : 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
